name: CI

on:
    workflow_dispatch:
    pull_request:
        branches: [ main ]

jobs:
    unit-tests:
        name: "Unit tests"
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Setup .NET SDKs
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: |
                        8.0.x
            -   name: Run unit tests (windows)
                if: matrix.os == 'windows-latest'
                run: ./build.ps1 CodeCoverage
            -   name: Run unit tests (ubuntu|macos)
                if: matrix.os != 'windows-latest'
                run: ./build.sh CodeCoverage
            -   name: Upload artifacts
                if: always()
                uses: actions/upload-artifact@v4
                with:
                    name: ${{ runner.os }}-artifacts
                    path: |
                        ./Artifacts/*
                        ./TestResults/*.trx
    
    api-tests:
        name: "API tests"
        runs-on: ubuntu-latest
        env:
            DOTNET_NOLOGO: true
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Setup .NET SDKs
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: |
                        8.0.x
            -   name: API checks
                run: ./build.sh ApiChecks
            -   name: Upload artifacts
                if: always()
                uses: actions/upload-artifact@v4
                with:
                    name: API-tests
                    path: |
                        ./Artifacts/*
                        ./TestResults/*.trx
    
    mutation-tests:
        name: "Mutation tests"
        if: ${{ github.actor != 'dependabot[bot]' }}
        runs-on: ubuntu-latest
        env:
            STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
            DOTNET_NOLOGO: true
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Setup .NET SDKs
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: |
                        8.0.x
            -   name: Run mutation tests
                run: ./build.sh MutationTests
    
    benchmarks:
        name: "Benchmarks"
        if: ${{ github.actor != 'dependabot[bot]' }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        env:
            DOTNET_NOLOGO: true
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Setup .NET SDKs
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: |
                        8.0.x
            -   name: Create benchmarks branch
                run: |
                    git config --global user.email "benchmarks@testably.org"
                    git config --global user.name "Benchmark User"
                    git switch benchmarks 2>/dev/null || git switch -c benchmarks;
                    git push --set-upstream origin benchmarks
                    git merge origin/main --no-edit
            -   name: Run benchmarks
                run: ./build.sh Benchmarks
            - name: Add comment to pull request
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              shell: bash
              run: |
                  prNumber="${{ github.event.number }}"
                  commentsUrl="https://api.github.com/repos/aweXpect/aweXpect/issues/$prNumber/comments"
                  identifierToken="BenchmarkDotNet v"
                  fileContent=$(<Artifacts/Benchmarks/results/aweXpect.Benchmarks.HappyCaseBenchmarks-report-github.md)
                  echo "$fileContent"
                  echo "Search for comment in PR#$prNumber containing $identifierToken..."
                  result=$(curl -X GET $commentsUrl \
                    -H "Content-Type: application/json" \
                    -H "Authorization: token $GITHUB_TOKEN")
                  if [[ $result != *"$identifierToken"* ]]
                  then
                    body="{\"body\":\"$fileContent\"}"
                    curl -X POST $commentsUrl \
                      -H "Accept: application/vnd.github+json" \
                      -H "Authorization: token $GITHUB_TOKEN" \
                  	  -d "$body"
                  fi
            -   name: Store benchmark result
                uses: rhysd/github-action-benchmark@v1
                with:
                    name: Benchmark.Net Benchmark
                    tool: 'benchmarkdotnet'
                    output-file-path: Artifacts/Benchmarks/results/aweXpect.Benchmarks.HappyCaseBenchmarks-report-full-compressed.json
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    fail-on-alert: true
                    alert-threshold: '150%'
                    comment-on-alert: true
                    auto-push: false
    
    static-code-analysis:
        name: "Static code analysis"
        if: ${{ github.actor != 'dependabot[bot]' }}
        runs-on: ubuntu-latest
        env:
            REPORTGENERATOR_LICENSE: ${{ secrets.REPORTGENERATOR_LICENSE }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            DOTNET_NOLOGO: true
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Setup .NET SDKs
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: |
                        8.0.x
            -   name: Run sonarcloud analysis
                run: ./build.sh CodeAnalysis
    
    publish-test-results:
        name: "Publish Tests Results"
        needs: [ api-tests, unit-tests ]
        runs-on: ubuntu-latest
        permissions:
            checks: write
            pull-requests: write
        if: always()
        steps:
            -   name: Download Artifacts
                uses: actions/download-artifact@v4
                with:
                    path: artifacts
            -   name: Publish Test Results
                uses: EnricoMi/publish-unit-test-result-action@v2
                with:
                    comment_mode: always
                    files: "artifacts/**/**/*.trx"
    
    build-pages:
        name: Build Pages
        if: ${{ github.actor != 'dependabot[bot]' }}
        runs-on: ubuntu-latest
        needs: [ benchmarks ]
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Merge benchmarks branch
                run: |
                    git config --global user.email "benchmarks@testably.org"
                    git config --global user.name "Benchmark User"
                    git fetch origin
                    git merge origin/benchmarks --no-edit
            -   uses: actions/setup-node@v4
                with:
                    node-version: 18
                    cache: npm
                    cache-dependency-path: ./Docs/pages/package-lock.json
            -   name: Install dependencies
                working-directory: ./Docs/pages
                run: npm ci
            -   name: Build website
                working-directory: ./Docs/pages
                run: npm run build
