name: Notify Docs Site

on:
    push:
        branches: [ main, benchmarks ]
        paths:
            - 'Docs/pages/**'
    workflow_dispatch:

jobs:
    dispatch:
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/benchmarks'
        name: Trigger Site rebuild
        runs-on: ubuntu-latest
        steps:
            -   name: Dispatch extension-documentation-updated-event to Testably/Testably.Site
                uses: peter-evans/repository-dispatch@v3
                with:
                    token: ${{ secrets.SITE_DISPATCH_TOKEN }}
                    repository: Testably/Testably.Site
                    event-type: extension-documentation-updated-event
                    client-payload: '{"source": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
